name: Callable workflow

on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Diag
        run: |
            echo "github.ref: ${{ github.ref  }}"
            echo "github.ref_name: ${{ github.ref_name  }}"
