name: Demonstrate github.ref_name difference

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
  workflow_dispatch: {} 

jobs:
  diag:
    runs-on: ubuntu-latest
    steps:
      - name: Diag
        run: |
            echo "github.ref: ${{ github.ref  }}"
            echo "github.ref_name: ${{ github.ref_name  }}"

  call:
    name: Call
    uses: ./.github/workflows/call.yaml
